### ISSUE TITLE
what does this do?

### ISSUE THREAD

**Issue by mafintosh** [mcollina/http-deduplicate#1]
the title of this module has two words that usually intrigue me but i'm not completely sure what this does

**Comment by mcollina** [comment]
it queues up http requests that you are already doing to avoid hitting the same endpoint multiple times.

Yes, I need to fill in a README and do a release :P.

**Comment by mcollina** [comment]
The end goal is to also have http cache here, so that you can really reduce the load on the target server and increase the latency. It's like a 3x perf booster.
